=== ITAgnesmeyer/EasyXMLSerializer/SRC/EasyXMLSerializerTests/testObjectToValidate.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT TestObject (StringValue,BoolValue,IntValue,ShortValue,
ByteValue,FloatValue,DoubleValue,DecimalValue,
DateTimeValue,ObjectValue)>
<!ATTLIST TestObject
xmlns CDATA #FIXED ''>

<!ELEMENT StringValue (#PCDATA)>
<!ATTLIST StringValue
xmlns CDATA #FIXED ''>

<!ELEMENT BoolValue (#PCDATA)>
<!ATTLIST BoolValue
xmlns CDATA #FIXED ''>

<!ELEMENT IntValue (#PCDATA)>
<!ATTLIST IntValue
xmlns CDATA #FIXED ''>

<!ELEMENT ShortValue (#PCDATA)>
<!ATTLIST ShortValue
xmlns CDATA #FIXED ''>

<!ELEMENT ByteValue (#PCDATA)>
<!ATTLIST ByteValue
xmlns CDATA #FIXED ''>

<!ELEMENT FloatValue (#PCDATA)>
<!ATTLIST FloatValue
xmlns CDATA #FIXED ''>

<!ELEMENT DoubleValue (#PCDATA)>
<!ATTLIST DoubleValue
xmlns CDATA #FIXED ''>

<!ELEMENT DecimalValue (#PCDATA)>
<!ATTLIST DecimalValue
xmlns CDATA #FIXED ''>

<!ELEMENT DateTimeValue (#PCDATA)>
<!ATTLIST DateTimeValue
xmlns CDATA #FIXED ''>

<!ELEMENT ObjectValue (#PCDATA)>
<!ATTLIST ObjectValue
xmlns CDATA #FIXED ''>

=== ITAgnesmeyer/EasyXMLSerializer/SRC/EasyXMLSerializerTests/testObjectToValidate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TestObject SYSTEM "testObjectToValidate.dtd">
<TestObject>
	<StringValue>string</StringValue>
	<BoolValue>true</BoolValue>
	<IntValue>1</IntValue>
	<ShortValue>200</ShortValue>
	<ByteValue>1</ByteValue>
	<FloatValue>1.5</FloatValue>
	<DoubleValue>1.6553</DoubleValue>
	<DecimalValue>1.3232</DecimalValue>
	<DateTimeValue>2020-05-30T00:00:00</DateTimeValue>
	<ObjectValue xsi:type="xsd:string">hallo</ObjectValue>
</TestObject>
